- hosts: default
  remote_user: sergio
  sudo: yes
  vars:
	TOKENBOT: "{{ lookup('env','TOKENBOT') }}"
	USR_BD: "{{ lookup('env','USR_BD') }}"
	PASS_BD: "{{ lookup('env','PASS_BD') }}"
  tasks:
  - name: Update
    command: apt-get update
  - name: essential
    command: apt-get install -y build-essential
  - name: Install git 
    command: apt-get install -y git
  - name: Instalar pip
    apt: name=python-pip state=present
  - name: Instalar paquetes necesarios
    apt: name=python-setuptools state=present
    apt: name=python-dev state=present
    apt: name=libgdbm-dev state=present
    apt: name=libncurses5-dev state=present
    apt: name=postgresql state=present
    apt: name=postgresql-contrib state=present
    apt: name=libpq-dev state=present
  - name: Clone 
    shell: rm -rf IV && git clone https://github.com/sergiocaceres/IV
  - name: Actualizar pip
    command: sudo pip install -U pip
    command: sudo apt-get install python-dev
  - name: Instalar requirements
    command: sudo pip install -r IV/requirements.txt
  - name: Execution
    shell: cd IV && python bot_telegram/bot.py
